let player = {
	quarks: new Decimal(0),
	accelerator: {
		unlocked: false,
		particlesUnlocked: false,
		protons: new Decimal(0),
		neutrons: new Decimal(0),
		electrons: new Decimal(0),
		hydrogen: new Decimal(0),
		protonUpgrades: [false,false,false,false],
		neutronUpgrades: [false,false,false,false],
		electronUpgrades: [false,false,false,false],
		hydrogenUpgrades: [0,0,0,0,0,0],
		elementUpgradeAutobuy: true,
	},
	format: {
		normalPrecision: 3,
		higherPrecision: 5,
		commasOnExponent: true,
		notation: 'Scientific',
		timeFormat: 'D:H:M:S',
		notationOnTime: false,
	},
	options: {
		simulateTime: true,
		offlineTicks: 4096,
		theme: 'Dark',
		hotkeys: true,
		saveNotifications: 'Manual saves only',
		achievementNotifications: 'Always',
		viewAchievements: 2,
		achievementMultiplier: true,
		viewCompletedRows: true,
		viewQuestionRows: true,
	},
	stats: {
		totalTime: 0,
		onlineTime: 0,
		totalQuarks: new Decimal(0),
	},
	achievements: [...Array(8)].map((x) => false),
	tab: 'main',
	lastUpdate: Date.now(),
};